name: Update Homebrew Formula

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number to update (e.g., 0.1.0)"
        required: true

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set version number
        id: set_version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Download and calculate SHA256 for Mac ARM
        run: |
          VERSION=${{ github.event.inputs.version }}
          FILE="endform-aarch64-apple-darwin.tar.gz"
          URL="https://cli.endform.dev/${VERSION}/endform-aarch64-apple-darwin/${FILE}"
          echo "Downloading $URL"
          curl -LO $URL
          SHA=$(sha256sum $FILE | awk '{print $1}')
          echo "MAC_ARM_URL=$URL" >> $GITHUB_ENV
          echo "MAC_ARM_SHA=$SHA" >> $GITHUB_ENV

      - name: Download and calculate SHA256 for Mac x86
        run: |
          VERSION=${{ github.event.inputs.version }}
          FILE="endform-x86_64-apple-darwin.tar.gz"
          URL="https://cli.endform.dev/${VERSION}/endform-x86_64-apple-darwin/${FILE}"
          echo "Downloading $URL"
          curl -LO $URL
          SHA=$(sha256sum $FILE | awk '{print $1}')
          echo "MAC_X86_URL=$URL" >> $GITHUB_ENV
          echo "MAC_X86_SHA=$SHA" >> $GITHUB_ENV

      - name: Download and calculate SHA256 for Linux ARM
        run: |
          VERSION=${{ github.event.inputs.version }}
          FILE="endform-aarch64-unknown-linux-gnu.tar.gz"
          URL="https://cli.endform.dev/${VERSION}/endform-aarch64-unknown-linux-gnu/${FILE}"
          echo "Downloading $URL"
          curl -LO $URL
          SHA=$(sha256sum $FILE | awk '{print $1}')
          echo "LINUX_ARM_URL=$URL" >> $GITHUB_ENV
          echo "LINUX_ARM_SHA=$SHA" >> $GITHUB_ENV

      - name: Download and calculate SHA256 for Linux x86
        run: |
          VERSION=${{ github.event.inputs.version }}
          FILE="endform-x86_64-unknown-linux-gnu.tar.gz"
          URL="https://cli.endform.dev/${VERSION}/endform-x86_64-unknown-linux-gnu/${FILE}"
          echo "Downloading $URL"
          curl -LO $URL
          SHA=$(sha256sum $FILE | awk '{print $1}')
          echo "LINUX_X86_URL=$URL" >> $GITHUB_ENV
          echo "LINUX_X86_SHA=$SHA" >> $GITHUB_ENV

      - name: Update endform.rb
        run: |
          sed -i "s|MAC_ARM_URL = .*|MAC_ARM_URL = \"${MAC_ARM_URL}\"|" endform.rb
          sed -i "s|MAC_ARM_SHA = .*|MAC_ARM_SHA = \"${MAC_ARM_SHA}\"|" endform.rb
          sed -i "s|MAC_X86_URL = .*|MAC_X86_URL = \"${MAC_X86_URL}\"|" endform.rb
          sed -i "s|MAC_X86_SHA = .*|MAC_X86_SHA = \"${MAC_X86_SHA}\"|" endform.rb
          sed -i "s|LINUX_ARM_URL = .*|LINUX_ARM_URL = \"${LINUX_ARM_URL}\"|" endform.rb
          sed -i "s|LINUX_ARM_SHA = .*|LINUX_ARM_SHA = \"${LINUX_ARM_SHA}\"|" endform.rb
          sed -i "s|LINUX_X86_URL = .*|LINUX_X86_URL = \"${LINUX_X86_URL}\"|" endform.rb
          sed -i "s|LINUX_X86_SHA = .*|LINUX_X86_SHA = \"${LINUX_X86_SHA}\"|" endform.rb

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add endform.rb
          git commit -m "Update endform.rb for version ${{ github.event.inputs.version }}"
          git push